version: 2
updates:
  - package-ecosystem: gomod
    directory: /vortelio
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: /vortelio-pip
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
